<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Uloc\ApiBundle\EventListener\ApiExceptionSubscriber' shared service.

return $this->services['Uloc\\ApiBundle\\EventListener\\ApiExceptionSubscriber'] = new \Uloc\ApiBundle\EventListener\ApiExceptionSubscriber(true, ($this->services['uloc_api.response_factory'] ?? ($this->services['uloc_api.response_factory'] = new \Uloc\ApiBundle\Api\ResponseFactory())), ($this->services['uloc_api.logger'] ?? $this->load('getUlocApi_LoggerService.php')));
