<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'uloc_api.key_loader' shared service.

return $this->services['uloc_api.key_loader'] = new \Uloc\ApiBundle\Services\JWT\KeyLoader\RawKeyLoader(($this->targetDirs[3].'\\tests/../var/jwt/private.pem'), ($this->targetDirs[3].'\\tests/../var/jwt/public.pem'), '');
