<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'uloc_api.token_get_command' shared autowired service.

return $this->services['uloc_api.token_get_command'] = new \Uloc\ApiBundle\Command\UlocTokenGetCommand('Doctrine\\ORM\\EntityManagerInterface', 'Uloc\\ApiBundle\\Services\\JWT\\Encoder\\JWTEncoderInterface');
