<?php

namespace Uloc\ApiBundle\Repository;

/**
 * AuthSecurityIpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthSecurityIpRepository extends \Doctrine\ORM\EntityRepository
{
}
