<?php

namespace Uloc\ApiBundle\Repository;

/**
 * AuthSecurityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthSecurityRepository extends \Doctrine\ORM\EntityRepository
{
}
