<?php

namespace Uloc\ApiBundle\Repository\Permission;

/**
 * ModulePermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulePermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
