<?php

namespace Uloc\ApiBundle\Repository\MessageService;

/**
 * MessageLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageLogRepository extends \Doctrine\ORM\EntityRepository
{
}
