<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'uloc_api.manager.person_manager' shared service.

return $this->services['uloc_api.manager.person_manager'] = new \Uloc\ApiBundle\Manager\PersonManager(new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0));
