<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'uloc_api.response_listener' shared service.

return $this->services['uloc_api.response_listener'] = new \Uloc\ApiBundle\EventListener\ResponseListener();
