<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'uloc_api.user_create_command' shared autowired service.

return $this->services['uloc_api.user_create_command'] = new \Uloc\ApiBundle\Command\UlocUserCreateCommand('Doctrine\\ORM\\EntityManagerInterface', 'Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface');
