<?php

namespace Uloc\ApiBundle\Repository\Chat;

/**
 * ChatGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
