<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQy5daA5\testsUloc_ApiBundle_Tests_UlocApiTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQy5daA5/testsUloc_ApiBundle_Tests_UlocApiTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQy5daA5.legacy');

    return;
}

if (!\class_exists(testsUloc_ApiBundle_Tests_UlocApiTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQy5daA5\testsUloc_ApiBundle_Tests_UlocApiTestingKernelTestDebugContainer::class, testsUloc_ApiBundle_Tests_UlocApiTestingKernelTestDebugContainer::class, false);
}

return new \ContainerQy5daA5\testsUloc_ApiBundle_Tests_UlocApiTestingKernelTestDebugContainer([
    'container.build_hash' => 'Qy5daA5',
    'container.build_id' => '9f57da26',
    'container.build_time' => 1564354744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQy5daA5');
