<?php

namespace Uloc\ApiBundle\Repository\App;

/**
 * TemplateCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
