<?php

namespace Uloc\ApiBundle\Repository\App;

/**
 * VariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableRepository extends \Doctrine\ORM\EntityRepository
{
}
