<?php

namespace Uloc\ApiBundle\Repository\Person;

/**
 * NoteHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
