<?php

namespace Uloc\ApiBundle\Repository\Person;

/**
 * TypePhonePurposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePhonePurposeRepository extends \Doctrine\ORM\EntityRepository
{
}
