<?php

namespace Uloc\ApiBundle\Repository\Person;

/**
 * TypePersonDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePersonDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
