<?php

namespace Uloc\ApiBundle\Repository\Person;

use Uloc\ApiBundle\Repository\BaseRepository;

/**
 * TypeEmailPurposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEmailPurposeRepository extends BaseRepository
{
}
