<?php

namespace Uloc\ApiBundle\Repository\Person;

/**
 * TypeEmailPurposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEmailPurposeRepository extends \Doctrine\ORM\EntityRepository
{
}
